/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class GameUI extends Laya.View {
		public normal:Laya.Sprite;
		public timebar:Laya.ProgressBar;
		public scorelabel:Laya.FontClip;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Game");
        }
    }
    REG("ui.GameUI",GameUI);
    export class GameOverUI extends Laya.View {
		public restartBtn:Laya.Button;
		public score:Laya.FontClip;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("GameOver");
        }
    }
    REG("ui.GameOverUI",GameOverUI);
    export class GameStartUI extends Laya.View {
		public btn_start:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("GameStart");
        }
    }
    REG("ui.GameStartUI",GameStartUI);
    export class HammerUI extends Laya.View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Hammer");
        }
    }
    REG("ui.HammerUI",HammerUI);
}