/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameView from "./script/GameView"
import GameOver from "./script/GameOver"
import GameStart from "./script/GameStart"
import Hammer from "./script/Hammer"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=800;
    static height:number=600;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="GameStart.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/GameView.ts",GameView);
        reg("script/GameOver.ts",GameOver);
        reg("script/GameStart.ts",GameStart);
        reg("script/Hammer.ts",Hammer);
    }
}
GameConfig.init();